config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root 'landing_page#index'
	resources :games, only: [:new, :create, :show] do 
		resources :pieces
	end
	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/piece.rb
class Piece < ApplicationRecord
  validates :game, presence: true
  belongs_to :game

  def is_obstructed?(new_x, new_y)
    horizontal_obstructed?(new_x) ||
    vertical_obstructed?(new_y) ||
    diagonal_obstructed?(new_x, new_y) ||
    invalid_move?(new_x, new_y)
  end
 
  def move_to!(new_x, new_y)
    # update piece attributes to new_x and new_y positions
    if !is_obstructed?(new_x, new_y)
      if landing_square_available?(new_x, new_y)
        self.update_attributes(x_position: new_x, y_position: new_y)

      elsif !landing_square_available?(new_x, new_y) && Piece.where(x_position: new_x, y_position: new_y, game_id: self.game_id).first.color == self.color
              # Invalid move
              raise[:notice] = "invalid move"
      else
        Piece.where(x_position: new_x, y_position: new_y, game_id: self.game_id).first.update_attributes(x_position: nil, y_position: nil, game_id: self.game_id)
        self.update_attributes(x_position: new_x, y_position: new_y, 
                               captured: true)
        # Captures piece present
      end
    else
      if is_obstructed?(new_x, new_y) == true
        raise[:notice] = "invalid move"
      end 
      # Invalid move due to obstructed path
    end  
  end

  private
  
  #Horizontal movement only
  def horizontal_obstructed?(new_x) 
    Piece.where(x_position:(self.x_position - 1...new_x),
                y_position:self.y_position, game_id: self.game_id).present? && 
    Piece.where(x_position:(self.x_position + 1..new_x),
                y_position:self.y_position, game_id: self.game_id).present?
  end

  #Vertical movement only
  def vertical_obstructed?(new_y)  
    Piece.where(y_position:(self.y_position - 1...new_y), 
                x_position:self.x_position, game_id: self.game_id).present? &&
    Piece.where(y_position:(self.y_position + 1...new_y),
                x_position:self.x_position, game_id: self.game_id).present?
  end

  #Diagonal movement only
  def diagonal_obstructed?(new_x, new_y)  
    Piece.where(y_position:(self.y_position - 1...new_y),
                x_position:(self.x_position - 1...new_x), game_id: self.game_id)
                .present? &&
    Piece.where(y_position:(self.y_position + 1...new_y),
                x_position:(self.x_position + 1...new_x), game_id: self.game_id)
                .present?
  end

  #Invalid movement (movement not horizontal, vertical, or diagonal)
  def invalid_move?(new_x, new_y) 
    if x_position == new_x && y_position == new_y
      return true
    elsif new_x < 1 || new_x > 8 || new_y < 1 || new_y > 8
      return true
    else
      return false
    end
  end

  def name
    self.class.to_s
  end
  
  def landing_square_available?(new_x, new_y)
    @move_to = Piece.where(x_position: new_x, y_position: new_y, 
                          game_id: self.game_id).take
    if @move_to == nil
      return true
    elsif @move_to.color == self.color
      return false
    elsif @move_to.color != self.color
    # Landing square is not available because the piece currently present must be captured to move here!
      return false
    else
      return false
    end
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
skip_before_action :verify_authenticity_token

	def show
		@piece = Piece.find(params[:id])
	end

	def update
		@piece = Piece.find(params[:id])
		@piece.update_attributes(piece_params)
    	redirect_to game_path(@piece.game)
	end

	def edit
		@piece = Piece.find_by_id(params[:id])
		@game = @piece.game
	end


	private

	def piece_params
		params.require(:piece).permit(:x_position, :y_position, :game_id, :color)
	end
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/edit.html.erb
<h1>move piece </h1>

<%= simple_form_for @piece, as: :piece, :url => game_piece_path do |f| %>
	<%= f.input :x_position %>
	<%= f.input :y_position %>
	<%= f.submit "update" %>
<% end %>

app/views/pieces/show.html.erb
<h1>move your piece</h1>

<table id="chessboard-2" class="chessboard">
  <!-- 1, 8 = top left -->
  <% (1..8).to_a.reverse.each do |i| %>
    <tr>
      <% (1..8).each do |j| %>

        <td data-y-pos="<%= i %>" data-x-pos="<%= j %>" style="position: relative">
          <% if @piece.x_position == j && @piece.y_position == i %>
            <div class="highlighted" style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; background-color: #f3fd71">
              <%= @piece.name %>

            </div>
          <% else %>
            <%= simple_form_for [@piece.game, @piece], as: :piece, url: game_piece_path(@piece.game, @piece) do |f| %>
              <%= f.input :x_position, as: :hidden, input_html: { value: j } %>
              <%= f.input :y_position, as: :hidden, input_html: { value: i } %>

              <%= f.submit "Move Here" %>
            <% end %>
            <%# "(#{i}, #{j})" %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>